package com.example.sheshield.models

import com.google.firebase.Timestamp
import com.google.firebase.firestore.PropertyName

data class Contact(
    @PropertyName("name")
    val name: String = "",

    @PropertyName("phone")
    val phone: String = "",

    @PropertyName("email")
    val email: String = "",


    @PropertyName("createdAt")
    val createdAt: Timestamp = Timestamp.now(),

    // This is auto-generated by Firestore, not stored in the document
    var id: String = ""
){
    // Helper function to check if contact is valid
    fun isValid(): Boolean {
        return name.trim().isNotEmpty() &&
                phone.trim().isNotEmpty() &&
                phone.length >= 10
    }

    // Optional: Convert to display string
    fun toDisplayString(): String {
        return "$name - $phone"
    }
}

data class UserContacts(
    val contacts: List<Contact> = emptyList()
)