package com.example.sheshield.models

import com.google.firebase.Timestamp
import com.google.firebase.firestore.PropertyName

data class Contact(
    @PropertyName("name")
    val name: String = "",

    @PropertyName("phone")
    val phone: String = "",

    @PropertyName("email")
    val email: String = "",

    @PropertyName("fcmToken")
    val fcmToken: String? = null, // NEW: For push notifications if contact has the app

    @PropertyName("createdAt")
    val createdAt: Timestamp = Timestamp.now(),

    // This is auto-generated by Firestore, not stored in the document
    var id: String = ""
) {
    // Helper function to check if contact is valid
    fun isValid(): Boolean {
        return name.trim().isNotEmpty() &&
                phone.trim().isNotEmpty() &&
                phone.length >= 10
    }

    // Optional: Convert to display string
    fun toDisplayString(): String {
        return "$name - $phone"
    }

    // NEW: Check if contact can receive push notifications
    fun canReceivePushNotification(): Boolean {
        return !fcmToken.isNullOrBlank()
    }

    // NEW: Check if contact has email
    fun hasEmail(): Boolean {
        return email.trim().isNotEmpty() && email.contains("@")
    }
}

data class UserContacts(
    val contacts: List<Contact> = emptyList()
)